import mongoose from 'mongoose';

const emergencyRequestSchema = new mongoose.Schema({
  id: { type: String, required: true, unique: true },
  patientName: { type: String, required: true },
  patientAge: { type: Number, default: 35 },
  patientGender: { type: String, default: 'Male' },
  patientId: { type: String, default: '' },
  doctorPatientId: { type: String, default: '' },
  verificationCode: { type: String, default: '' },
  isVerifiedByHospital: { type: Boolean, default: false },
  selectedChannels: [{ type: String }],
  channelStatuses: { type: Object, default: {} },
  fulfilledChannel: { type: String, default: '' },
  bloodGroup: { type: String, required: true },
  bloodComponent: { type: String, default: 'PRBC' },
  unitsNeeded: { type: Number, required: true },
  unitsFulfilled: { type: Number, default: 0 },
  confirmedUnits: { type: Number, default: 0 },
  urgency: { type: String, enum: ['CRITICAL', 'HIGH', 'URGENT', 'MODERATE', 'NORMAL', 'LOW'], default: 'URGENT' },
  hospitalName: { type: String, required: true },
  hospitalAddress: { type: String, default: '' },
  wardDept: { type: String, default: '' },
  state: { type: String, default: 'Karnataka' },
  district: { type: String, default: 'Dharwad' },
  city: { type: String, required: true },
  pincode: { type: String, default: '580030' },
  contactPerson: { type: String, required: true },
  maskedPhone: { type: String, default: '' },
  contactPhone: { type: String, required: true },
  contactEmail: { type: String, default: '' },
  relationship: { type: String, default: 'Kin' },
  requestedAt: { type: String, required: true },
  requiredDate: { type: String, default: '' },
  requiredTime: { type: String, default: '' },
  deadline: { type: String, required: true },
  reason: { type: String, default: '' },
  medicalReasonCategory: { type: String, default: '' },
  customReason: { type: String, default: '' },
  additionalNotes: { type: String, default: '' },
  doctorName: { type: String, default: '' },
  prescriptionUrl: { type: String, default: '' },
  prescriptionFileName: { type: String, default: '' },
  status: { type: String, required: true },
  aiUrgencyScore: { type: Number, default: 85 },
  decayScore: { type: Number, default: 90 },
  trendingReason: { type: String, default: '' },
  donorResponses: [{ type: Object, default: [] }],
  matchedDonorsCount: { type: Number, default: 0 },
  timeline: [{ type: Object, default: [] }],
  createdAt: { type: Date, default: Date.now }
});

export const EmergencyRequest = mongoose.models.EmergencyRequest || mongoose.model('EmergencyRequest', emergencyRequestSchema);

